//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1184.0 using the following command:
// xscgen https://schemas.xmlsoap.org/ws/2006/02/devprof/devicesprofile.xsd --nc

using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace Ws.Addressing
{
    
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("EndpointReferenceType", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlInclude(typeof(EndpointReference))]
    [XmlInclude(typeof(FaultTo))]
    [XmlInclude(typeof(From))]
    [XmlInclude(typeof(ReplyTo))]
    public partial class EndpointReferenceType
    {
        
        [Required(AllowEmptyStrings=true)]
        [XmlElement("Address")]
        public AttributedUri Address { get; set; }
        
        [XmlElement("ReferenceProperties")]
        public ReferencePropertiesType ReferenceProperties { get; set; }
        
        [XmlElement("ReferenceParameters")]
        public ReferenceParametersType ReferenceParameters { get; set; }
        
        [XmlElement("PortType")]
        public AttributedQName PortType { get; set; }
        
        [XmlElement("ServiceName")]
        public ServiceNameType ServiceName { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlElement> _any;
        
        /// <summary>
        /// <para>If "Policy" elements from namespace "http://schemas.xmlsoap.org/ws/2002/12/policy#policy" are used, they must appear first (before any extensibility elements).</para>
        /// </summary>
        [Description(("If \"Policy\" elements from namespace \"http://schemas.xmlsoap.org/ws/2002/12/policy" +
                      "#policy\" are used, they must appear first (before any extensibility elements)."))]
        [XmlAnyElement()]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="EndpointReferenceType" /> class.</para>
        /// </summary>
        public EndpointReferenceType()
        {
            this._any = new Collection<XmlElement>();
            this._anyAttribute = new Collection<XmlAttribute>();
        }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("AttributedURI", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlInclude(typeof(Action))]
    [XmlInclude(typeof(MessageId))]
    [XmlInclude(typeof(To))]
    public partial class AttributedUri
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlText()]
        public string Value { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="AttributedUri" /> class.</para>
        /// </summary>
        public AttributedUri()
        {
            this._anyAttribute = new Collection<XmlAttribute>();
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("ReferencePropertiesType", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ReferencePropertiesType
    {
        
        [XmlIgnore()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElement()]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ReferencePropertiesType" /> class.</para>
        /// </summary>
        public ReferencePropertiesType()
        {
            this._any = new Collection<XmlElement>();
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("ReferenceParametersType", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ReferenceParametersType
    {
        
        [XmlIgnore()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElement()]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ReferenceParametersType" /> class.</para>
        /// </summary>
        public ReferenceParametersType()
        {
            this._any = new Collection<XmlElement>();
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("AttributedQName", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class AttributedQName
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlText()]
        public XmlQualifiedName Value { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="AttributedQName" /> class.</para>
        /// </summary>
        public AttributedQName()
        {
            this._anyAttribute = new Collection<XmlAttribute>();
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("ServiceNameType", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ServiceNameType
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlText()]
        public XmlQualifiedName Value { get; set; }
        
        [XmlAttribute("PortName")]
        public string PortName { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ServiceNameType" /> class.</para>
        /// </summary>
        public ServiceNameType()
        {
            this._anyAttribute = new Collection<XmlAttribute>();
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("Relationship", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("RelatesTo", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class Relationship
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlText()]
        public string Value { get; set; }
        
        [XmlAttribute("RelationshipType")]
        public XmlQualifiedName RelationshipType { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Relationship" /> class.</para>
        /// </summary>
        public Relationship()
        {
            this._anyAttribute = new Collection<XmlAttribute>();
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("RelationshipTypeValues", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public enum RelationshipTypeValues
    {
        
        [XmlEnum("wsa:Reply")]
        WsaReply,
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("ReplyAfterType", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("ReplyAfter", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class ReplyAfterType
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlText()]
        public string Value { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ReplyAfterType" /> class.</para>
        /// </summary>
        public ReplyAfterType()
        {
            this._anyAttribute = new Collection<XmlAttribute>();
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("RetryAfterType", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("RetryAfter", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class RetryAfterType
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlText()]
        public string Value { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RetryAfterType" /> class.</para>
        /// </summary>
        public RetryAfterType()
        {
            this._anyAttribute = new Collection<XmlAttribute>();
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("FaultSubcodeValues", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public enum FaultSubcodeValues
    {
        
        [XmlEnum("wsa:InvalidMessageInformationHeader")]
        WsaInvalidMessageInformationHeader,
        
        [XmlEnum("wsa:MessageInformationHeaderRequired")]
        WsaMessageInformationHeaderRequired,
        
        [XmlEnum("wsa:DestinationUnreachable")]
        WsaDestinationUnreachable,
        
        [XmlEnum("wsa:ActionNotSupported")]
        WsaActionNotSupported,
        
        [XmlEnum("wsa:EndpointUnavailable")]
        WsaEndpointUnavailable,
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("To", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class To : AttributedUri
    {
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("MessageID", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("MessageID", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class MessageId : AttributedUri
    {
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("Action", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class Action : AttributedUri
    {
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("From", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class From : EndpointReferenceType
    {
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("EndpointReference", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class EndpointReference : EndpointReferenceType
    {
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("ReplyTo", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class ReplyTo : EndpointReferenceType
    {
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("FaultTo", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class FaultTo : EndpointReferenceType
    {
    }
}
