//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1184.0 using the following command:
// xscgen https://schemas.xmlsoap.org/ws/2006/02/devprof/devicesprofile.xsd --nc

using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;
using Ws.Addressing;

namespace Ws.Devprof
{
    
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("ThisModelType", Namespace="http://schemas.xmlsoap.org/ws/2006/02/devprof")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("ThisModel", Namespace="http://schemas.xmlsoap.org/ws/2006/02/devprof")]
    public partial class ThisModelType
    {
        
        [XmlIgnore()]
        private Collection<LocalizedStringType> _manufacturer;
        
        [Required(AllowEmptyStrings=true)]
        [XmlElement("Manufacturer")]
        public Collection<LocalizedStringType> Manufacturer
        {
            get
            {
                return _manufacturer;
            }
            private set
            {
                _manufacturer = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ThisModelType" /> class.</para>
        /// </summary>
        public ThisModelType()
        {
            this._manufacturer = new Collection<LocalizedStringType>();
            this._modelName = new Collection<LocalizedStringType>();
            this._any = new Collection<XmlElement>();
            this._anyAttribute = new Collection<XmlAttribute>();
        }
        
        [XmlElement("ManufacturerUrl")]
        public string ManufacturerUrl { get; set; }
        
        [XmlIgnore()]
        private Collection<LocalizedStringType> _modelName;
        
        [Required(AllowEmptyStrings=true)]
        [XmlElement("ModelName")]
        public Collection<LocalizedStringType> ModelName
        {
            get
            {
                return _modelName;
            }
            private set
            {
                _modelName = value;
            }
        }
        
        [XmlElement("ModelNumber")]
        public string ModelNumber { get; set; }
        
        [XmlElement("ModelUrl")]
        public string ModelUrl { get; set; }
        
        [XmlElement("PresentationUrl")]
        public string PresentationUrl { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElement()]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("LocalizedStringType", Namespace="http://schemas.xmlsoap.org/ws/2006/02/devprof")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class LocalizedStringType
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlText()]
        public string Value { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="LocalizedStringType" /> class.</para>
        /// </summary>
        public LocalizedStringType()
        {
            this._anyAttribute = new Collection<XmlAttribute>();
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("ThisDeviceType", Namespace="http://schemas.xmlsoap.org/ws/2006/02/devprof")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("ThisDevice", Namespace="http://schemas.xmlsoap.org/ws/2006/02/devprof")]
    public partial class ThisDeviceType
    {
        
        [XmlIgnore()]
        private Collection<LocalizedStringType> _friendlyName;
        
        [Required(AllowEmptyStrings=true)]
        [XmlElement("FriendlyName")]
        public Collection<LocalizedStringType> FriendlyName
        {
            get
            {
                return _friendlyName;
            }
            private set
            {
                _friendlyName = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ThisDeviceType" /> class.</para>
        /// </summary>
        public ThisDeviceType()
        {
            this._friendlyName = new Collection<LocalizedStringType>();
            this._any = new Collection<XmlElement>();
            this._anyAttribute = new Collection<XmlAttribute>();
        }
        
        [XmlElement("FirmwareVersion")]
        public string FirmwareVersion { get; set; }
        
        [XmlElement("SerialNumber")]
        public string SerialNumber { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElement()]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("DeviceRelationshipTypeURIs", Namespace="http://schemas.xmlsoap.org/ws/2006/02/devprof")]
    public enum DeviceRelationshipTypeUrIs
    {
        
        [XmlEnum("http://schemas.xmlsoap.org/ws/2006/02/devprof/host")]
        HttpSchemasXmlsoapOrgWs200602DevprofHost,
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("DeviceMetadataDialectURIs", Namespace="http://schemas.xmlsoap.org/ws/2006/02/devprof")]
    public enum DeviceMetadataDialectUrIs
    {
        
        [XmlEnum("http://schemas.xmlsoap.org/ws/2006/02/devprof/ThisModel")]
        HttpSchemasXmlsoapOrgWs200602DevprofThisModel,
        
        [XmlEnum("http://schemas.xmlsoap.org/ws/2006/02/devprof/ThisDevice")]
        HttpSchemasXmlsoapOrgWs200602DevprofThisDevice,
        
        [XmlEnum("http://schemas.xmlsoap.org/ws/2006/02/devprof/Relationship")]
        HttpSchemasXmlsoapOrgWs200602DevprofRelationship,
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("DeviceEventingFilterDialectURIs", Namespace="http://schemas.xmlsoap.org/ws/2006/02/devprof")]
    public enum DeviceEventingFilterDialectUrIs
    {
        
        [XmlEnum("http://schemas.xmlsoap.org/ws/2006/02/devprof/Action")]
        HttpSchemasXmlsoapOrgWs200602DevprofAction,
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("DeviceActionURIs", Namespace="http://schemas.xmlsoap.org/ws/2006/02/devprof")]
    public enum DeviceActionUrIs
    {
        
        [XmlEnum("http://schemas.xmlsoap.org/ws/2006/02/devprof/Fault")]
        HttpSchemasXmlsoapOrgWs200602DevprofFault,
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("DeviceSoapFaultSubcodeQNames", Namespace="http://schemas.xmlsoap.org/ws/2006/02/devprof")]
    public enum DeviceSoapFaultSubcodeQNames
    {
        
        [XmlEnum("tns:FilterActionNotSupported")]
        TnsFilterActionNotSupported,
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("HostServiceType", Namespace="http://schemas.xmlsoap.org/ws/2006/02/devprof")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlInclude(typeof(Host))]
    [XmlInclude(typeof(Hosted))]
    public partial class HostServiceType
    {
        
        [XmlIgnore()]
        private Collection<EndpointReferenceType> _endpointReference;
        
        [Required(AllowEmptyStrings=true)]
        [XmlElement("EndpointReference", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
        public Collection<EndpointReferenceType> EndpointReference
        {
            get
            {
                return _endpointReference;
            }
            private set
            {
                _endpointReference = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HostServiceType" /> class.</para>
        /// </summary>
        public HostServiceType()
        {
            this._endpointReference = new Collection<EndpointReferenceType>();
            this._types = new Collection<string>();
            this._any = new Collection<XmlElement>();
            this._anyAttribute = new Collection<XmlAttribute>();
        }
        
        [XmlIgnore()]
        private Collection<string> _types;
        
        [XmlElement("Types")]
        public Collection<string> Types
        {
            get
            {
                return _types;
            }
            private set
            {
                _types = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Types collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool TypesSpecified
        {
            get
            {
                return (this.Types.Count != 0);
            }
        }
        
        [Required(AllowEmptyStrings=true)]
        [XmlElement("ServiceId")]
        public string ServiceId { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElement()]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("DiscoveryTypeValues", Namespace="http://schemas.xmlsoap.org/ws/2006/02/devprof")]
    public enum DiscoveryTypeValues
    {
        
        [XmlEnum("tns:Device")]
        TnsDevice,
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("AssertionType", Namespace="http://schemas.xmlsoap.org/ws/2006/02/devprof")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("Profile", Namespace="http://schemas.xmlsoap.org/ws/2006/02/devprof")]
    public partial class AssertionType
    {
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="AssertionType" /> class.</para>
        /// </summary>
        public AssertionType()
        {
            this._anyAttribute = new Collection<XmlAttribute>();
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("Relationship", Namespace="http://schemas.xmlsoap.org/ws/2006/02/devprof", AnonymousType=true)]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("Relationship", Namespace="http://schemas.xmlsoap.org/ws/2006/02/devprof")]
    public partial class Relationship
    {
        
        [XmlIgnore()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElement()]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Relationship" /> class.</para>
        /// </summary>
        public Relationship()
        {
            this._any = new Collection<XmlElement>();
            this._anyAttribute = new Collection<XmlAttribute>();
        }
        
        [Required(AllowEmptyStrings=true)]
        [XmlAttribute("Type")]
        public string Type { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("Hosted", Namespace="http://schemas.xmlsoap.org/ws/2006/02/devprof")]
    public partial class Hosted : HostServiceType
    {
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("Host", Namespace="http://schemas.xmlsoap.org/ws/2006/02/devprof")]
    public partial class Host : HostServiceType
    {
    }
}
