//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1184.0 using the following command:
// xscgen https://schemas.xmlsoap.org/ws/2004/08/eventing/eventing.xsd --nc

using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Xml;
using System.Xml.Schema;
using System.Xml.Serialization;
using Ws.Addressing;

namespace Ws.Eventing
{
    
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("DeliveryType", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class DeliveryType
    {
        
        [XmlIgnore()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElement()]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="DeliveryType" /> class.</para>
        /// </summary>
        public DeliveryType()
        {
            this._any = new Collection<XmlElement>();
            this._anyAttribute = new Collection<XmlAttribute>();
        }
        
        [XmlAttribute("Mode")]
        public string Mode { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
        
        [XmlText()]
        public string[] Text { get; set; }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("FilterType", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class FilterType
    {
        
        [XmlIgnore()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElement()]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="FilterType" /> class.</para>
        /// </summary>
        public FilterType()
        {
            this._any = new Collection<XmlElement>();
            this._anyAttribute = new Collection<XmlAttribute>();
        }
        
        [XmlAttribute("Dialect")]
        public string Dialect { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
        
        [XmlText()]
        public string[] Text { get; set; }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("LanguageSpecificStringType", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class LanguageSpecificStringType
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlText()]
        public string Value { get; set; }
        
        [XmlAttribute("lang", Namespace="http://www.w3.org/XML/1998/namespace", Form=XmlSchemaForm.Qualified)]
        public string Lang { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="LanguageSpecificStringType" /> class.</para>
        /// </summary>
        public LanguageSpecificStringType()
        {
            this._anyAttribute = new Collection<XmlAttribute>();
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("SubscriptionEndCodeType", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public enum SubscriptionEndCodeType
    {
        
        [XmlEnum("http://schemas.xmlsoap.org/ws/2004/08/eventing/DeliveryFailure")]
        HttpSchemasXmlsoapOrgWs200408EventingDeliveryFailure,
        
        [XmlEnum("http://schemas.xmlsoap.org/ws/2004/08/eventing/SourceShuttingDown")]
        HttpSchemasXmlsoapOrgWs200408EventingSourceShuttingDown,
        
        [XmlEnum("http://schemas.xmlsoap.org/ws/2004/08/eventing/SourceCancelling")]
        HttpSchemasXmlsoapOrgWs200408EventingSourceCancelling,
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("NotifyTo", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class NotifyTo : EndpointReferenceType
    {
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("Subscribe", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing", AnonymousType=true)]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("Subscribe", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class Subscribe
    {
        
        [XmlElement("EndTo")]
        public EndpointReferenceType EndTo { get; set; }
        
        [Required(AllowEmptyStrings=true)]
        [XmlElement("Delivery")]
        public DeliveryType Delivery { get; set; }
        
        [XmlElement("Expires")]
        public string Expires { get; set; }
        
        [XmlElement("Filter")]
        public FilterType Filter { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElement()]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Subscribe" /> class.</para>
        /// </summary>
        public Subscribe()
        {
            this._any = new Collection<XmlElement>();
            this._anyAttribute = new Collection<XmlAttribute>();
        }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("SubscribeResponse", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing", AnonymousType=true)]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("SubscribeResponse", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class SubscribeResponse
    {
        
        [Required(AllowEmptyStrings=true)]
        [XmlElement("SubscriptionManager")]
        public EndpointReferenceType SubscriptionManager { get; set; }
        
        [Required(AllowEmptyStrings=true)]
        [XmlElement("Expires")]
        public string Expires { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElement()]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="SubscribeResponse" /> class.</para>
        /// </summary>
        public SubscribeResponse()
        {
            this._any = new Collection<XmlElement>();
            this._anyAttribute = new Collection<XmlAttribute>();
        }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("Renew", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing", AnonymousType=true)]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("Renew", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class Renew
    {
        
        [XmlElement("Expires")]
        public string Expires { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElement()]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Renew" /> class.</para>
        /// </summary>
        public Renew()
        {
            this._any = new Collection<XmlElement>();
            this._anyAttribute = new Collection<XmlAttribute>();
        }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("RenewResponse", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing", AnonymousType=true)]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("RenewResponse", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class RenewResponse
    {
        
        [XmlElement("Expires")]
        public string Expires { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElement()]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RenewResponse" /> class.</para>
        /// </summary>
        public RenewResponse()
        {
            this._any = new Collection<XmlElement>();
            this._anyAttribute = new Collection<XmlAttribute>();
        }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("GetStatus", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing", AnonymousType=true)]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("GetStatus", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class GetStatus
    {
        
        [XmlIgnore()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElement()]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="GetStatus" /> class.</para>
        /// </summary>
        public GetStatus()
        {
            this._any = new Collection<XmlElement>();
            this._anyAttribute = new Collection<XmlAttribute>();
        }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("GetStatusResponse", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing", AnonymousType=true)]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("GetStatusResponse", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class GetStatusResponse
    {
        
        [XmlElement("Expires")]
        public string Expires { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElement()]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="GetStatusResponse" /> class.</para>
        /// </summary>
        public GetStatusResponse()
        {
            this._any = new Collection<XmlElement>();
            this._anyAttribute = new Collection<XmlAttribute>();
        }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("Unsubscribe", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing", AnonymousType=true)]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("Unsubscribe", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class Unsubscribe
    {
        
        [XmlIgnore()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElement()]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Unsubscribe" /> class.</para>
        /// </summary>
        public Unsubscribe()
        {
            this._any = new Collection<XmlElement>();
            this._anyAttribute = new Collection<XmlAttribute>();
        }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("SubscriptionEnd", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing", AnonymousType=true)]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("SubscriptionEnd", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class SubscriptionEnd
    {
        
        [Required(AllowEmptyStrings=true)]
        [XmlElement("SubscriptionManager")]
        public EndpointReferenceType SubscriptionManager { get; set; }
        
        [Required(AllowEmptyStrings=true)]
        [XmlElement("Status")]
        public string Status { get; set; }
        
        [XmlIgnore()]
        private Collection<LanguageSpecificStringType> _reason;
        
        [XmlElement("Reason")]
        public Collection<LanguageSpecificStringType> Reason
        {
            get
            {
                return _reason;
            }
            private set
            {
                _reason = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Reason collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool ReasonSpecified
        {
            get
            {
                return (this.Reason.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="SubscriptionEnd" /> class.</para>
        /// </summary>
        public SubscriptionEnd()
        {
            this._reason = new Collection<LanguageSpecificStringType>();
            this._any = new Collection<XmlElement>();
            this._anyAttribute = new Collection<XmlAttribute>();
        }
        
        [XmlIgnore()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElement()]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
    }
}
