//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1184.0 using the following command:
// xscgen https://schemas.xmlsoap.org/ws/2004/09/mex/MetadataExchange.xsd --nc

using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace Ws.Mex
{
    
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("GetMetadata", Namespace="http://schemas.xmlsoap.org/ws/2004/09/mex", AnonymousType=true)]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("GetMetadata", Namespace="http://schemas.xmlsoap.org/ws/2004/09/mex")]
    public partial class GetMetadata
    {
        
        [XmlElement("Dialect")]
        public string Dialect { get; set; }
        
        [XmlElement("Identifier")]
        public string Identifier { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="GetMetadata" /> class.</para>
        /// </summary>
        public GetMetadata()
        {
            this._anyAttribute = new Collection<XmlAttribute>();
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("Metadata", Namespace="http://schemas.xmlsoap.org/ws/2004/09/mex", AnonymousType=true)]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("Metadata", Namespace="http://schemas.xmlsoap.org/ws/2004/09/mex")]
    public partial class Metadata
    {
        
        [XmlIgnore()]
        private Collection<MetadataSection> _metadataSection;
        
        [XmlElement("MetadataSection")]
        public Collection<MetadataSection> MetadataSection
        {
            get
            {
                return _metadataSection;
            }
            private set
            {
                _metadataSection = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the MetadataSection collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool MetadataSectionSpecified
        {
            get
            {
                return (this.MetadataSection.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Metadata" /> class.</para>
        /// </summary>
        public Metadata()
        {
            this._metadataSection = new Collection<MetadataSection>();
            this._any = new Collection<XmlElement>();
            this._anyAttribute = new Collection<XmlAttribute>();
        }
        
        [XmlIgnore()]
        private Collection<XmlElement> _any;
        
        [XmlAnyElement()]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("MetadataSection", Namespace="http://schemas.xmlsoap.org/ws/2004/09/mex", AnonymousType=true)]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("MetadataSection", Namespace="http://schemas.xmlsoap.org/ws/2004/09/mex")]
    public partial class MetadataSection
    {
        
        [XmlAnyElement()]
        public XmlElement Any { get; set; }
        
        [XmlElement("MetadataReference")]
        public MetadataReference MetadataReference { get; set; }
        
        [XmlElement("Location")]
        public string Location { get; set; }
        
        [Required(AllowEmptyStrings=true)]
        [XmlAttribute("Dialect")]
        public string Dialect { get; set; }
        
        [XmlAttribute("Identifier")]
        public string Identifier { get; set; }
        
        [XmlIgnore()]
        private Collection<XmlAttribute> _anyAttribute;
        
        [XmlAnyAttribute()]
        public Collection<XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MetadataSection" /> class.</para>
        /// </summary>
        public MetadataSection()
        {
            this._anyAttribute = new Collection<XmlAttribute>();
        }
    }
    
    [GeneratedCode("XmlSchemaClassGenerator", "2.1.1184.0")]
    [Serializable()]
    [XmlType("MetadataReference", Namespace="http://schemas.xmlsoap.org/ws/2004/09/mex", AnonymousType=true)]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("MetadataReference", Namespace="http://schemas.xmlsoap.org/ws/2004/09/mex")]
    public partial class MetadataReference
    {
        
        [XmlIgnore()]
        private Collection<XmlElement> _any;
        
        [Required(AllowEmptyStrings=true)]
        [XmlAnyElement()]
        public Collection<XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MetadataReference" /> class.</para>
        /// </summary>
        public MetadataReference()
        {
            this._any = new Collection<XmlElement>();
        }
    }
}
