//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1184.0 using the following command:
// xscgen https://schemas.xmlsoap.org/ws/2004/08/eventing/eventing.xsd --nc
namespace Xml.Namespace
{
    
}
